services:
  app:
    image: ghcr.io/bavragor/${DOCKER_IMAGE_TAG:-vite-sveltekit-docker-template:latest}
    container_name: docker-pnpm-sveltekit
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-20.17.0}
        PNPM_VERSION: ${PNPM_VERSION:-9.10.0}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - '${EXTERNAL_PORT_DEV:-80}:5173'
      - '${EXTERNAL_PORT:-8080}:4173'
    volumes:
      - .:/home/node/app
      - /home/node/app/.pnpm-store
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - .env
    restart: 'unless-stopped'
    tty: true
