services:
  app:
    depends_on:
      - database
    profiles:
      - default
      - full
    image: ghcr.io/${GITHUB_ACTOR:-tony-stark-eth}/${DOCKER_IMAGE_TAG:-notomo:latest}
    container_name: notomo
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-20.17.0}
        PNPM_VERSION: ${PNPM_VERSION:-9.10.0}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - '${EXTERNAL_PORT_DEV:-80}:5173'
      - '${EXTERNAL_PORT:-8080}:4173'
    volumes:
      - .:/home/node/app
      - /home/node/app/.pnpm-store
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - .env.docker
    restart: 'unless-stopped'
    tty: true
  database:
    profiles:
      - default
      - full
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${DATABASE_USER:-notomo}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-notomo-pw}
      POSTGRES_DB: ${DATABASE_NAME:-notomo}

  adminer:
    profiles:
      - full
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8000}:8080
