name: CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '.git-hooks/*'
      - '.github/**'
      - '!.github/workflows/ci.yaml'
      - '!.github/workflows/docker-bake.yaml'
      - '.gitignore'
      - '**.md'
      - 'Makefile*'

  push:
    branches:
      - main
      - release@*
    paths-ignore:
      - '.git-hooks/*'
      - '.github/**'
      - '!.github/workflows/ci.yaml'
      - '!.github/workflows/docker-bake.yaml'
      - '.gitignore'
      - '**.md'
      - 'Makefile*'

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ci-${{ github.ref_name == 'main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  docker-bake:
    uses: ./.github/workflows/docker-bake.yaml
    permissions:
      contents: read
      id-token: write
      pull-requests: read
      packages: write

  code-style:
    runs-on: ubuntu-latest
    needs: docker-bake
    timeout-minutes: 15
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Prepare Docker Workspace
        id: docker-prepare-workspace
        uses: ./.github/actions/docker-prepare-workspace
        with:
          docker-image-tag: ${{ needs.docker-bake.outputs.docker-image-tag }}
          docker-compose-services: 'app'
          make-init-targets-before: 'setup'
          make-init-targets-after: 'install'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Svelte Check
        run: docker compose exec app pnpm run lint

      - name: Run Svelte Check
        run: docker compose exec app pnpm run check

  tests:
    runs-on: ubuntu-latest
    needs: docker-bake
    timeout-minutes: 25
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Prepare Docker Workspace
        id: docker-prepare-workspace
        uses: ./.github/actions/docker-prepare-workspace
        with:
          docker-image-tag: ${{ needs.docker-bake.outputs.docker-image-tag }}
          make-init-targets-before: 'setup'
          make-init-targets-after: 'install'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Test Suite
        run: docker compose exec app pnpm run test

      - name: Run E2E Test Suite
        run: docker compose exec app pnpm run test:e2e
